TT.WebTab/Controllers/TabController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TT.Dto;
using TT.Negocio;
using TT.WebTab.Models;
using TT.Uils.MapperBase;
using TT.Negocio.Logs;
using TT.WebTab.Security;

namespace TT.WebTab.Controllers
{
    public class TabController : Controller
    {

        [HttpPost]
        public ActionResult VozIncident(VozIncidentModel modelo)
        {
            try
            {
                int CodigoTelefonia = new claDatosProducto().BuscarTelefonia(modelo._IdAsunto);
                CP_ConsultarDatosProductoDto CP_ConsultarDatosProductoModel = null;
                if (ModelState.IsValid) {
                    CP_ConsultarDatosProductoModel = new claDatosProducto().MetConsultar(CodigoTelefonia);
                    CP_ConsultarDatosProductoModel.VCHCOMENTARIOS = modelo._Comentarios;
                    TempData["CP_ConsultarDatosProductoModel"] = CP_ConsultarDatosProductoModel;
                }
            } catch (Exception ex)
            {
                log.error(ex, "EJT4940A", "TabController - VozIncident");
                ViewBag.eror = new ErrorGeneralModel() { lugarError = "TabController - VozIncident" };
            }
            return RedirectToAction("DetalleDatosProducto");
        }
        
         public ActionResult DetalleDatosProducto(CP_UsersLogTabTelefonia _usersLogTabTelefonia) {
            CP_ConsultarDatosProductoDto CP_ConsultarDatosProductoModelBase = TempData["CP_ConsultarDatosProductoModel"] as CP_ConsultarDatosProductoDto;
            DetalleHeaderModel _DetalleHeaderModel = null;
            _DetalleHeaderModel = MapperConfigurationCentral<CP_ConsultarDatosProductoDto, DetalleHeaderModel>.MapEntity(CP_ConsultarDatosProductoModelBase);
            DetalleDatosProductoModel CP_ConsultarDatosProductoModelView = new DetalleDatosProductoModel();
            CP_ConsultarDatosProductoModelView._DetalleHeaderProductsModel = _DetalleHeaderModel;
            if (CP_ConsultarDatosProductoModelView._DetalleHeaderProductsModel == null){
                if (_usersLogTabTelefonia.vchDetailId == 0){
                    ViewBag._VozIncidentDto = MapperConfigurationCentral<CP_VozIncidentDto, VozIncidentModel>.MapEntity(new claClienteTelefonia().MetVozIncident(_usersLogTabTelefonia));
                }
                else if (_usersLogTabTelefonia.vchDetailId != 0 && !string.IsNullOrEmpty(_usersLogTabTelefonia.vchAlternateId)) {
                    // return redireciconar al controlador que pinte la pantalla segundaria 
                }
            }
            return View(CP_ConsultarDatosProductoModelView);

        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult DetalleDatosProducto(DetalleDatosProductoModel model)
        {
           if(String.IsNullOrEmpty(model._DetalleHeaderProductsModel.VCHDESCRIPCIONUSO) && String.IsNullOrEmpty(model._DetalleHeaderProductsModel.VCHNOMBREESTRATO))
            {
                //mensaje "Debe configurar el estrato y uso de servicio."
            }
            int respuesta = 0;
            CP_ConsultarDatosProductoDto ConsultarDatosProductoDto = null;
            ConsultarDatosProductoDto = MapperConfigurationCentral<DetalleDatosProductoModel,
                CP_ConsultarDatosProductoDto>.MapEntity(model);
            if(ConsultarDatosProductoDto.IPRODUCTID == null)
                ConsultarDatosProductoDto.IPRODUCTID = "0";

            if(ConsultarDatosProductoDto.CHPRODUCTNUMBER == null)
                ConsultarDatosProductoDto.CHPRODUCTNUMBER = "0";
            if (model._DetalleHeaderProductsModel.IDATOSPRODUCTOID == 0)
                respuesta = new claDatosProducto().MetInsertar(ConsultarDatosProductoDto);
           else
                respuesta = new claDatosProducto().MetActualizar(ConsultarDatosProductoDto);
           
            return View(model);

        }

        public ActionResult TiposLinea(DetalleDatosProductoModel model) {
            // para activar la parcial de tiposLinea

            var ObjetoNegocioTipoLinea = new TiposLinea();
            model._TiposLinea = new TiposLineaModel
            {
                AuxGrupoCentrex = ObjetoNegocioTipoLinea.ConsultaGrupoCentrex(),
                AuxCallSource = ObjetoNegocioTipoLinea.ConsultavchCallSource()
            };

            //Se hace un parseo de List a SelectListItem para enviarlo a la vista y pueda ser leido por el DropDawnList
            //model._TiposLinea.GrupoCentrex = auxGrupoCentrex.Select(x => new SelectListItem()
            //{
            //    Value = x,
            //    Text = x
            //}).ToList();

            //model._TiposLinea.CallSource = new List<SelectListItem>();
            //List<string> auxCallSource = ObjetoNegocioTipoLinea.ConsultavchCallSource();
            //foreach (string call in auxCallSource)
            //{
            //    model._TiposLinea.CallSource.Add(new SelectListItem
            //    {
            //        Text = call,
            //        Value = call
            //    });
            //}



            TiposLineaEdicionModel _TiposLineaEdicion = new TiposLineaEdicionModel();
            List<TiposLineaEdicionModel> listaLinea = new List<TiposLineaEdicionModel>();

            // Lleno una lista para que esta sea mostrada en la tabla
            listaLinea.Add(new TiposLineaEdicionModel
            {
                IdTipoLinea = 111,
                TipoLineaSelected = false,
                IdVenta = 1,
                CampoUno = 2,
                CanalesActivos = 3,
                CampoDos = 4,
                CampoTres = 5,
                DireccionIp = "123.0.0.1",
                Ciudad = "Bogota",
                SubRed = "23.56.89.12",
                Publicar = true,
                ComparteNumeracion = false,
                ModeloEquipo = "New",
                Entrada = true,
                Puerto = "9090",
                NumeroInicial = 1,
                NumeroFinal = 99,
                Troncal = 45,
                ShortNumber = 34,
                Exento = true,
                SolicitudOperacion = "New",
                ResultadoOpercion = "Old",
                ComentarioResultado = "No apply",
                CanalesEntrantes = 2,
                CanalesSalientes = 3
            });
            listaLinea.Add(new TiposLineaEdicionModel
            {
                IdTipoLinea = 222,
                TipoLineaSelected = false,
                IdVenta = 2,
                CampoUno = 2,
                CanalesActivos = 3,
                CampoDos = 4,
                CampoTres = 5,
                DireccionIp = "123.0.0.1",
                Ciudad = "Bogota",
                SubRed = "23.56.89.12",
                Publicar = true,
                ComparteNumeracion = false,
                ModeloEquipo = "New",
                Entrada = true,
                Puerto = "9090",
                NumeroInicial = 1,
                NumeroFinal = 99,
                Troncal = 45,
                ShortNumber = 34,
                Exento = true,
                SolicitudOperacion = "New",
                ResultadoOpercion = "Old",
                ComentarioResultado = "No apply",
                CanalesEntrantes = 2,
                CanalesSalientes = 3
            });
            listaLinea.Add(new TiposLineaEdicionModel
            {
                IdTipoLinea = 333,
                TipoLineaSelected = false,
                IdVenta = 3,
                CampoUno = 2,
                CanalesActivos = 3,
                CampoDos = 4,
                CampoTres = 5,
                DireccionIp = "123.0.0.1",
                Ciudad = "Bogota",
                SubRed = "23.56.89.12",
                Publicar = true,
                ComparteNumeracion = false,
                ModeloEquipo = "New",
                Entrada = true,
                Puerto = "9090",
                NumeroInicial = 1,
                NumeroFinal = 99,
                Troncal = 45,
                ShortNumber = 34,
                Exento = true,
                SolicitudOperacion = "New",
                ResultadoOpercion = "Old",
                ComentarioResultado = "No apply",
                CanalesEntrantes = 2,
                CanalesSalientes = 3
            });

            model._ListTiposLineaEdicion = listaLinea;

            model._TiposLineaEdicion = _TiposLineaEdicion;
            return View(model);
        }

        [HttpPost]
        public ActionResult TiposLinea(TiposLineaModel tipos)
        {
            
            if (ModelState.IsValid)
            {
                
            }
            return View(tipos);
        }
    }
}

TT.WebTab/Views/Tab/ConfigurarTipoLinea.cshtml
@model TT.WebTab.Models.TiposLineaEdicionModel

<div class="container">
    <br />
    <div class="row">
        <div class="col-md-2">
            @Html.LabelFor(model => model.IdProducto, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-2">
            @Html.EditorFor(model => model.IdProducto, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
        </div>
        <div class="col-md-8">
            @Html.EditorFor(model => model.NombreProducto, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
        </div>
    </div>

    <br />
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-3">
            @Html.LabelFor(model => model.TipoDeLinea, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-6">
            @Html.DropDownListFor(model => model.TipoDeLinea, ViewBag.lista as List<SelectListItem>, "-- Seleccione --", new { @class = "form-control" })
        </div>
    </div>

    <br />
    <div class="row">
        <div class="col-md-1">
            @Html.LabelFor(model => model.CampoUno, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-5">
            @Html.DropDownListFor(model => model.CampoUno, ViewBag.lista as List<SelectListItem>, "-- Seleccione --", new { @class = "form-control" })
        </div>
        <div class="col-md-1">
            @Html.LabelFor(model => model.Puerto, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-5">
            @Html.EditorFor(model => model.Puerto, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
        </div>
    </div>

    <br />
    <div class="row">
        <div class="col-md-1">
            @Html.LabelFor(model => model.CanalesActivos, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-5">
            @Html.EditorFor(model => model.CanalesActivos, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
        </div>
        <div class="col-md-1">
            @Html.LabelFor(model => model.NumeroInicial, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-5">
            @Html.DropDownListFor(model => model.NumeroInicial, ViewBag.lista as List<SelectListItem>, "-- Seleccione --", new { @class = "form-control" })
        </div>
    </div>

    <br />
    <div class="row">
        <div class="col-md-1">
            @Html.LabelFor(model => model.CampoDos, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-5">
            @Html.DropDownListFor(model => model.CampoDos, ViewBag.lista as List<SelectListItem>, "-- Seleccione --", new { @class = "form-control" })
        </div>
        <div class="col-md-1">
            @Html.LabelFor(model => model.NumeroFinal, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-5">
            @Html.DropDownListFor(model => model.NumeroFinal, ViewBag.lista as List<SelectListItem>, "-- Seleccione --", new { @class = "form-control" })
        </div>
    </div>

    <br />
    <div class="row">
        <div class="col-md-1">
            @Html.LabelFor(model => model.CampoTres, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-5">
            @Html.DropDownListFor(model => model.CampoTres, ViewBag.lista as List<SelectListItem>, "-- Seleccione --", new { @class = "form-control" })
        </div>
        <div class="col-md-1">
            @Html.LabelFor(model => model.Troncal, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-5">
            @Html.EditorFor(model => model.Troncal, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
        </div>
    </div>

    <br />
    <div class="row">
        <div class="col-md-1">
            @Html.LabelFor(model => model.DireccionIp, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-5">
            @Html.DropDownListFor(model => model.DireccionIp, ViewBag.lista as List<SelectListItem>, "-- Seleccione --", new { @class = "form-control" })
        </div>
        <div class="col-md-1">
            @Html.LabelFor(model => model.ShortNumber, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-5">
            @Html.EditorFor(model => model.ShortNumber, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
        </div>
    </div>

    <br />
    <div class="row">
        <div class="col-md-1">
            @Html.LabelFor(model => model.Ciudad, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-5">
            @Html.DropDownListFor(model => model.Ciudad, ViewBag.lista as List<SelectListItem>, "-- Seleccione --", new { @class = "form-control" })
        </div>
        <div class="col-md-1">
            @Html.LabelFor(model => model.Exento, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-5">
            @Html.DropDownListFor(model => model.Exento, ViewBag.lista as List<SelectListItem>, "-- Seleccione --", new { @class = "form-control" })
        </div>
    </div>

    <br />
    <div class="row">
        <div class="col-md-1">
            @Html.LabelFor(model => model.SubRed, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-5">
            @Html.DropDownListFor(model => model.SubRed, ViewBag.lista as List<SelectListItem>, "-- Seleccione --", new { @class = "form-control" })
        </div>
        <div class="col-md-1">
            @Html.LabelFor(model => model.SolicitudOperacion, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-5">
            @Html.DropDownListFor(model => model.SolicitudOperacion, ViewBag.lista as List<SelectListItem>, "-- Seleccione --", new { @class = "form-control" })
        </div>
    </div>

    <br />
    <div class="row">
        <div class="col-md-1">
            @Html.LabelFor(model => model.Publicar, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-5">
            @Html.DropDownListFor(model => model.Publicar, ViewBag.lista as List<SelectListItem>, "-- Seleccione --", new { @class = "form-control" })
        </div>
        <div class="col-md-1">
            @Html.LabelFor(model => model.ResultadoOpercion, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-5">
            @Html.DropDownListFor(model => model.ResultadoOpercion, ViewBag.lista as List<SelectListItem>, "-- Seleccione --", new { @class = "form-control" })
        </div>
    </div>

    <br />
    <div class="row">
        <div class="col-md-1">
            @Html.LabelFor(model => model.ModeloEquipo, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-5">
            @Html.DropDownListFor(model => model.ModeloEquipo, ViewBag.lista as List<SelectListItem>, "-- Seleccione --", new { @class = "form-control" })
        </div>
        <div class="col-md-1">
            @Html.LabelFor(model => model.CanalesEntrantes, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-5">
            @Html.EditorFor(model => model.CanalesEntrantes, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
        </div>
    </div>

    <br />
    <div class="row">
        <div class="col-md-1">
            @Html.LabelFor(model => model.Entrada, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-5">
            @Html.DropDownListFor(model => model.Entrada, ViewBag.lista as List<SelectListItem>, "-- Seleccione --", new { @class = "form-control" })
        </div>
        <div class="col-md-1">
            @Html.LabelFor(model => model.CanalesSalientes, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-5">
            @Html.EditorFor(model => model.CanalesSalientes, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
        </div>
    </div>

    <br />
    <div class="row">
        <div class="col-md-1">
            @Html.LabelFor(model => model.ComparteNumeracion, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-5">
            @Html.DropDownListFor(model => model.ComparteNumeracion, ViewBag.lista as List<SelectListItem>, "-- Seleccione --", new { @class = "form-control" })
        </div>
        <div class="col-md-1">
            @Html.LabelFor(model => model.ComentarioResultado, htmlAttributes: new { @class = "control-label " })
        </div>
        <div class="col-md-5">
            @Html.TextAreaFor(model => model.ComentarioResultado, new { @class = "form-control", rows = "5" })
        </div>
    </div>

    <br />
    <div class="row">
        <div class="col-md-6 text-center p-3">
            @Html.ActionLink("Cancelar", "tiposLinea", null,null, new { @class= "btn btn-outline-danger", style="width:50%"})
        </div>
        <div class="col-md-6 text-center p-3">
            <input type="submit" value="Guardar" class="btn btn-outline-danger" style="width:50%"/>
        </div>
    </div>
</div>

TT.WebTab/Views/Tab/Index.cshtml
<div class="row">
    <div class="col-md-4">
        <h2>Empecemos!</h2>
        <p>
            Principal del Tab telefonia
        </p>
    </div>
  
</div>

TT.WebTab/Views/Tab/tiposLinea.cshtml
@model TT.WebTab.Models.DetalleDatosProductoModel
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/Content/bootstrap.css")


@{Layout = null; }
<div class="container estilo-letra">
    <nav>
        <div class="nav nav-pills" id="pills-tab" role="tablist">
            <a class="nav-item nav-link active" id="nav-TiposLinea-tab" data-toggle="tab" href="#nav-TiposLinea" role="tab" aria-controls="nav-TiposLinea" aria-selected="true">Tipos de Linea</a>
            <a class="nav-item nav-link " id="nav-NumeracionPublica-tab" data-toggle="tab" href="#nav-NumeracionPublica" role="tab" aria-controls="nav-NumeracionPublica" aria-selected="false">Numeración Publica</a>
        </div>
    </nav>

    <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-TiposLinea" role="tabpanel" aria-labelledby="nav-TiposLinea-tab">
            <div class="row">
                <div class="col-md-5">
                    <h6 class="text-danger p-3">TIPOS DE LINEA ACTUALES EN EL CLIENTE</h6>
                </div>
                @using (Html.BeginForm("PostTiposLinea", "Tab", FormMethod.Post))
                {
                    <div class="col-md-5 row">
                        @Html.LabelFor(model => model._TiposLinea.CallSource, htmlAttributes: new { @class = "col-form-label  col-md-5", @style = "width: 100%;" })
                        <div class="col-md-7">
                            @Html.EditorFor(model => model._TiposLinea.CallSource, new { htmlAttributes = new { @class = "form-control input-call-source" } })
                            @Html.ValidationMessageFor(model => model._TiposLinea.CallSource, "", new { @class = "text-danger" })
                            <div class="div-call-source div-hide" on,>
                                @Html.Label("Numeros Call Source que se encuentran en uso")
                                @foreach (var item in Model._TiposLinea.AuxCallSource)
                                {
                                    <p>@item</p>
                                }
                            </div>
                        </div>
                        <br />
                        @Html.LabelFor(model => model._TiposLinea.GrupoCentrex, htmlAttributes: new { @class = "col-form-label col-md-5" })
                        <div class="col-md-7">
                            @*@Html.DropDownListFor(model => model._TiposLinea.IdGrupoCentrex, Model._TiposLinea.GrupoCentrex, htmlAttributes: new { @class = "form-control" } )*@
                            @Html.EditorFor(model => model._TiposLinea.GrupoCentrex, new { htmlAttributes = new { @class = "form-control input-grupo-centrex" } })
                            @Html.ValidationMessageFor(model => model._TiposLinea.GrupoCentrex, "", new { @class = "text-danger" })
                            <div class="div-grupo-centrex div-hide" on,>
                                @Html.Label("Numeros Grupo Centrex que se encuentran en uso")
                                @foreach (var item in Model._TiposLinea.AuxGrupoCentrex)
                                {
                                    <div>@item</div>
                                }
                            </div>
                        </div>
                    </div>
                    <div class="col-md-2 row text-center">
                        <input type="submit" value="Guardar" class="btn degrade-azul btn-sombra" />
                        <input type="submit" value="Liberar Recurso" class="btn  degrade-azul btn-sombra" />
                    </div>
                }
            </div>

            @Html.Partial("_TablaTiposLinea", Model)

            <div class="p-5"></div>
            <div class="row ">
                <div class="col-md-7 row">
                    @Html.LabelFor(model => model._TiposLineaEdicion.IdProducto, htmlAttributes: new { @class = "col-form-label col-md-3 bg-red rounded text-white" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model._TiposLineaEdicion.IdProducto, new { htmlAttributes = new { @class = "form-control", disabled = true } })
                    </div>
                    <div class="col-md-6">
                        @Html.EditorFor(model => model._TiposLineaEdicion.NombreProducto, new { htmlAttributes = new { @class = "form-control", disabled = true } })
                    </div>

                </div>
                <div class="col-md-5 row">
                    @Html.LabelFor(model => model._TiposLineaEdicion.IdVenta, "Incidente que esta modificando", htmlAttributes: new { @class = "col-form-label col-md-8 bg-red rounded text-white" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model._TiposLineaEdicion.IdVenta, new { htmlAttributes = new { @class = "form-control", disabled = true } })
                    </div>

                </div>
            </div>

            @Html.Partial("_TablaTiposLinea")

            <div class="row">
                @Html.ActionLink("Agregar tipo de linea", "ConfigurarTipoLinea", null, null, new { @class = "btn btn-outline-danger btn-redondo btn-sombra" })
            </div>
        </div>
        <div class="tab-pane fade" id="nav-NumeracionPublica" role="tabpanel" aria-labelledby="nav-NumeracionPublica-tab">

        </div>
    </div>
</div>
<script src="~/Scripts/jquery-3.0.0.min.js"></script>
<script>

    $('.input-grupo-centrex').on('focusin', function () {
        $('.div-grupo-centrex').addClass('div-show');
        $('.div-grupo-centrex').removeClass('div-hide');
    });

    $('.div-grupo-centrex').on('blur', function () {
        $('.div-grupo-centrex').removeClass('div-show');
        $('.div-grupo-centrex').addClass('div-hide');
    });

    $('.input-call-source').on('focusin', function () {
        $('.div-call-source').addClass('div-show');
        $('.div-call-source').removeClass('div-hide');
    });

    $('.div-call-source').on('blur', function () {
        $('.div-call-source').removeClass('div-show');
        $('.div-call-source').addClass('div-hide');
    });

</script>